sudo apt-get install python3-pyorbital
sudo apt-get install python3-matplotlib
sudo apt-get install python3-scipy
sudo apt-get install python3-pip
sudo apt-get install libproj-dev
sudo apt-get install libgeos-dev
sudo apt-get install python3-pip
pip install --upgrade pip
sudo pip3 install cython
sudo pip3 install cartopy
