# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dpl_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DPL(object):
    def setupUi(self, DPL):
        DPL.setObjectName("DPL")
        DPL.resize(632, 323)
        self.verticalLayout = QtWidgets.QVBoxLayout(DPL)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(DPL)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.frame_4)
        self.frame.setMinimumSize(QtCore.QSize(190, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_1 = QtWidgets.QLabel(self.frame)
        self.label_1.setObjectName("label_1")
        self.verticalLayout_2.addWidget(self.label_1)
        self.curr_sats_lst = QtWidgets.QListWidget(self.frame)
        self.curr_sats_lst.setObjectName("curr_sats_lst")
        self.verticalLayout_2.addWidget(self.curr_sats_lst)
        self.horizontalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.frame_4)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame_4)
        self.frame_3.setMinimumSize(QtCore.QSize(190, 0))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.deployer_name_lbl = QtWidgets.QLabel(self.frame_3)
        self.deployer_name_lbl.setObjectName("deployer_name_lbl")
        self.verticalLayout_4.addWidget(self.deployer_name_lbl)
        self.mass_box1 = QtWidgets.QLineEdit(self.frame_3)
        self.mass_box1.setObjectName("mass_box1")
        self.verticalLayout_4.addWidget(self.mass_box1)
        self.name_box = QtWidgets.QLineEdit(self.frame_3)
        self.name_box.setObjectName("name_box")
        self.verticalLayout_4.addWidget(self.name_box)
        self.cat_box = QtWidgets.QLineEdit(self.frame_3)
        self.cat_box.setObjectName("cat_box")
        self.verticalLayout_4.addWidget(self.cat_box)
        self.mass_box2 = QtWidgets.QLineEdit(self.frame_3)
        self.mass_box2.setObjectName("mass_box2")
        self.verticalLayout_4.addWidget(self.mass_box2)
        self.spdx_box = QtWidgets.QLineEdit(self.frame_3)
        self.spdx_box.setObjectName("spdx_box")
        self.verticalLayout_4.addWidget(self.spdx_box)
        self.spdy_box = QtWidgets.QLineEdit(self.frame_3)
        self.spdy_box.setObjectName("spdy_box")
        self.verticalLayout_4.addWidget(self.spdy_box)
        self.spdz_box = QtWidgets.QLineEdit(self.frame_3)
        self.spdz_box.setObjectName("spdz_box")
        self.verticalLayout_4.addWidget(self.spdz_box)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame_4)
        self.deploy_now_bt = QtWidgets.QPushButton(DPL)
        self.deploy_now_bt.setObjectName("deploy_now_bt")
        self.verticalLayout.addWidget(self.deploy_now_bt)

        self.retranslateUi(DPL)
        QtCore.QMetaObject.connectSlotsByName(DPL)

    def retranslateUi(self, DPL):
        _translate = QtCore.QCoreApplication.translate
        DPL.setWindowTitle(_translate("DPL", "Dialog"))
        self.label_1.setText(_translate("DPL", "Current satellites:"))
        self.label_2.setText(_translate("DPL", "Satellite deployer:"))
        self.label_3.setText(_translate("DPL", "Deployer\'s mass [kg]:"))
        self.label_4.setText(_translate("DPL", "New sat\'s name:"))
        self.label_5.setText(_translate("DPL", "New sat\'s category:"))
        self.label_6.setText(_translate("DPL", "New sat\'s mass [kg]:"))
        self.label_7.setText(_translate("DPL", "Deployment speed x [m/s]:"))
        self.label_8.setText(_translate("DPL", "Deployment speed y [m/s]:"))
        self.label_9.setText(_translate("DPL", "Deployment speed z [m/s]:"))
        self.deployer_name_lbl.setText(_translate("DPL", "No sat selected"))
        self.deploy_now_bt.setText(_translate("DPL", "Deploy"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DPL = QtWidgets.QDialog()
    ui = Ui_DPL()
    ui.setupUi(DPL)
    DPL.show()
    sys.exit(app.exec_())
