# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1263, 713)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_2 = QtWidgets.QFrame(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.dpl_button = QtWidgets.QPushButton(self.frame_2)
        self.dpl_button.setObjectName("dpl_button")
        self.horizontalLayout_3.addWidget(self.dpl_button)
        self.loc_button = QtWidgets.QPushButton(self.frame_2)
        self.loc_button.setObjectName("loc_button")
        self.horizontalLayout_3.addWidget(self.loc_button)
        self.prev_day = QtWidgets.QToolButton(self.frame_2)
        self.prev_day.setObjectName("prev_day")
        self.horizontalLayout_3.addWidget(self.prev_day)
        self.prev_min = QtWidgets.QToolButton(self.frame_2)
        self.prev_min.setObjectName("prev_min")
        self.horizontalLayout_3.addWidget(self.prev_min)
        self.play = QtWidgets.QToolButton(self.frame_2)
        self.play.setObjectName("play")
        self.horizontalLayout_3.addWidget(self.play)
        self.next_min = QtWidgets.QToolButton(self.frame_2)
        self.next_min.setObjectName("next_min")
        self.horizontalLayout_3.addWidget(self.next_min)
        self.next_day = QtWidgets.QToolButton(self.frame_2)
        self.next_day.setObjectName("next_day")
        self.horizontalLayout_3.addWidget(self.next_day)
        self.datetime = QtWidgets.QDateTimeEdit(self.frame_2)
        self.datetime.setObjectName("datetime")
        self.horizontalLayout_3.addWidget(self.datetime)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_4.addWidget(self.frame_2)
        self.frame_plot = QtWidgets.QFrame(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_plot.sizePolicy().hasHeightForWidth())
        self.frame_plot.setSizePolicy(sizePolicy)
        self.frame_plot.setMaximumSize(QtCore.QSize(1180, 16777215))
        self.frame_plot.setObjectName("frame_plot")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_plot)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_4.addWidget(self.frame_plot)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_bot = QtWidgets.QFrame(self.tab_2)
        self.frame_bot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_bot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bot.setObjectName("frame_bot")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_bot)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.frame_bot)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 1, 9, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.frame_bot)
        self.label_35.setObjectName("label_35")
        self.gridLayout.addWidget(self.label_35, 2, 10, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.frame_bot)
        self.label_38.setObjectName("label_38")
        self.gridLayout.addWidget(self.label_38, 2, 13, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.frame_bot)
        self.label_31.setObjectName("label_31")
        self.gridLayout.addWidget(self.label_31, 2, 5, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.frame_bot)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 1, 8, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.frame_bot)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 1, 12, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.frame_bot)
        self.label_32.setObjectName("label_32")
        self.gridLayout.addWidget(self.label_32, 2, 7, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_bot)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_bot)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_bot)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_bot)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_bot)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_bot)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 1, 1, 1)
        self.label_1 = QtWidgets.QLabel(self.frame_bot)
        self.label_1.setObjectName("label_1")
        self.gridLayout.addWidget(self.label_1, 0, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_bot)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 0, 12, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_bot)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_bot)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame_bot)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame_bot)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 0, 5, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame_bot)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 0, 11, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.frame_bot)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 0, 9, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame_bot)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 0, 7, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.frame_bot)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 0, 13, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame_bot)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 0, 8, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame_bot)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 0, 10, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_bot)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 4, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.frame_bot)
        self.label_37.setObjectName("label_37")
        self.gridLayout.addWidget(self.label_37, 2, 12, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.frame_bot)
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 2, 4, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.frame_bot)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 1, 5, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.frame_bot)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 1, 13, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.frame_bot)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 1, 4, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.frame_bot)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 1, 11, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.frame_bot)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 1, 7, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.frame_bot)
        self.label_36.setObjectName("label_36")
        self.gridLayout.addWidget(self.label_36, 2, 11, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.frame_bot)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 1, 10, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.frame_bot)
        self.label_33.setObjectName("label_33")
        self.gridLayout.addWidget(self.label_33, 2, 8, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.frame_bot)
        self.label_34.setObjectName("label_34")
        self.gridLayout.addWidget(self.label_34, 2, 9, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_bot)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_bot)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.frame_bot)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1263, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuChange_planet = QtWidgets.QMenu(self.menuView)
        self.menuChange_planet.setObjectName("menuChange_planet")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionUpdate_TLE_from_net = QtWidgets.QAction(MainWindow)
        self.actionUpdate_TLE_from_net.setObjectName("actionUpdate_TLE_from_net")
        self.actionUpdate_TLE_from_file = QtWidgets.QAction(MainWindow)
        self.actionUpdate_TLE_from_file.setObjectName("actionUpdate_TLE_from_file")
        self.actionEnable_database = QtWidgets.QAction(MainWindow)
        self.actionEnable_database.setObjectName("actionEnable_database")
        self.actionAdd_south_atlantic_anomaly = QtWidgets.QAction(MainWindow)
        self.actionAdd_south_atlantic_anomaly.setObjectName("actionAdd_south_atlantic_anomaly")
        self.actionRemove_coverage = QtWidgets.QAction(MainWindow)
        self.actionRemove_coverage.setObjectName("actionRemove_coverage")
        self.actionAdd_remove_satellites = QtWidgets.QAction(MainWindow)
        self.actionAdd_remove_satellites.setObjectName("actionAdd_remove_satellites")
        self.actionFullscreen = QtWidgets.QAction(MainWindow)
        self.actionFullscreen.setObjectName("actionFullscreen")
        self.actionEarth = QtWidgets.QAction(MainWindow)
        self.actionEarth.setObjectName("actionEarth")
        self.actionMars = QtWidgets.QAction(MainWindow)
        self.actionMars.setObjectName("actionMars")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuEdit.addAction(self.actionUpdate_TLE_from_net)
        self.menuEdit.addAction(self.actionUpdate_TLE_from_file)
        self.menuEdit.addAction(self.actionEnable_database)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionAdd_south_atlantic_anomaly)
        self.menuEdit.addAction(self.actionRemove_coverage)
        self.menuEdit.addAction(self.actionAdd_remove_satellites)
        self.menuChange_planet.addAction(self.actionEarth)
        self.menuChange_planet.addAction(self.actionMars)
        self.menuView.addAction(self.actionFullscreen)
        self.menuView.addAction(self.menuChange_planet.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.actionExit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyPredict"))
        self.dpl_button.setText(_translate("MainWindow", "Simulate deployment"))
        self.loc_button.setText(_translate("MainWindow", "Simulate localization"))
        self.prev_day.setText(_translate("MainWindow", "|◀◀"))
        self.prev_min.setText(_translate("MainWindow", "|◀"))
        self.play.setText(_translate("MainWindow", "▶️"))
        self.next_min.setText(_translate("MainWindow", "▶️|"))
        self.next_day.setText(_translate("MainWindow", "▶️▶️|"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.label_25.setText(_translate("MainWindow", "TextLabel"))
        self.label_35.setText(_translate("MainWindow", "TextLabel"))
        self.label_38.setText(_translate("MainWindow", "TextLabel"))
        self.label_31.setText(_translate("MainWindow", "TextLabel"))
        self.label_24.setText(_translate("MainWindow", "TextLabel"))
        self.label_28.setText(_translate("MainWindow", "TextLabel"))
        self.label_32.setText(_translate("MainWindow", "TextLabel"))
        self.label_7.setText(_translate("MainWindow", "Latitude"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.label_8.setText(_translate("MainWindow", "TextLabel"))
        self.label_9.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "Category"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.label_1.setText(_translate("MainWindow", "Satellite"))
        self.label_19.setText(_translate("MainWindow", "ω"))
        self.label_10.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "Longitude"))
        self.label_11.setText(_translate("MainWindow", "TextLabel"))
        self.label_13.setText(_translate("MainWindow", "Spd. [m/s]"))
        self.label_18.setText(_translate("MainWindow", "i"))
        self.label_16.setText(_translate("MainWindow", "e"))
        self.label_14.setText(_translate("MainWindow", "a [km]"))
        self.label_20.setText(_translate("MainWindow", "T. Anom."))
        self.label_15.setText(_translate("MainWindow", "h [km²/s]"))
        self.label_17.setText(_translate("MainWindow", "Ω"))
        self.label_12.setText(_translate("MainWindow", "Alt. [km]"))
        self.label_37.setText(_translate("MainWindow", "TextLabel"))
        self.label_30.setText(_translate("MainWindow", "TextLabel"))
        self.label_22.setText(_translate("MainWindow", "TextLabel"))
        self.label_29.setText(_translate("MainWindow", "TextLabel"))
        self.label_21.setText(_translate("MainWindow", "TextLabel"))
        self.label_27.setText(_translate("MainWindow", "TextLabel"))
        self.label_23.setText(_translate("MainWindow", "TextLabel"))
        self.label_36.setText(_translate("MainWindow", "TextLabel"))
        self.label_26.setText(_translate("MainWindow", "TextLabel"))
        self.label_33.setText(_translate("MainWindow", "TextLabel"))
        self.label_34.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.menuFile.setTitle(_translate("MainWindow", "Fi&le"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuEdit.setTitle(_translate("MainWindow", "E&dit"))
        self.menuView.setTitle(_translate("MainWindow", "&View"))
        self.menuChange_planet.setTitle(_translate("MainWindow", "&Change planet"))
        self.actionExit.setText(_translate("MainWindow", "&Exit"))
        self.actionAbout.setText(_translate("MainWindow", "&About"))
        self.actionOpen.setText(_translate("MainWindow", "&Open"))
        self.actionSave_as.setText(_translate("MainWindow", "&Save as"))
        self.actionUpdate_TLE_from_net.setText(_translate("MainWindow", "&Update TLE from net"))
        self.actionUpdate_TLE_from_file.setText(_translate("MainWindow", "Update TLE &from file"))
        self.actionEnable_database.setText(_translate("MainWindow", "&Enable database"))
        self.actionAdd_south_atlantic_anomaly.setText(_translate("MainWindow", "&Add south atlantic anomaly"))
        self.actionRemove_coverage.setText(_translate("MainWindow", "&Remove coverage"))
        self.actionAdd_remove_satellites.setText(_translate("MainWindow", "A&dd/remove satellites"))
        self.actionFullscreen.setText(_translate("MainWindow", "&Fullscreen"))
        self.actionEarth.setText(_translate("MainWindow", "&Earth"))
        self.actionMars.setText(_translate("MainWindow", "&Mars"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
